"""feedback timestamp

Revision ID: 7249596a1c67
Revises: c433b1f84c90
Create Date: 2024-11-27 13:54:39.265724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7249596a1c67'
down_revision: Union[str, None] = 'c433b1f84c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'timestamp')
    # ### end Alembic commands ###
