"""favorite timestamp

Revision ID: b9afa32f4836
Revises: 7249596a1c67
Create Date: 2024-11-27 20:21:52.387722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9afa32f4836'
down_revision: Union[str, None] = '7249596a1c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'timestamp')
    # ### end Alembic commands ###
