"""signed datetime column for contract

Revision ID: c433b1f84c90
Revises: e549c012e8e0
Create Date: 2024-11-27 13:43:11.906111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c433b1f84c90'
down_revision: Union[str, None] = 'e549c012e8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('signed_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signed_datetime')
    # ### end Alembic commands ###
